Repository opensearch-project/common-utils, pull requests merged in 2021-12, with the labels that each got.

#104 Bumping common utils to 1.2.2.0
  .github/workflows/ci.yml
  build.gradle
Labels: v1.2.2

#105 Incremented version to 1.2.3.
  .github/workflows/ci.yml
  build.gradle
Labels: v1.2.3

#107 Incremented version to 1.2.4.
  .github/workflows/ci.yml
  build.gradle
Labels: v1.2.4
