Repository opensearch-project/common-utils, pull requests merged in 2022-10, with the labels that each got.

#263 remove force snakeyaml removal
  build.gradle
Labels: backport 2.3

#265 disable detekt so that snakeyaml <= 1.31 is not used
  build.gradle
Labels: backport 1.3

#225 Added legacy support for SNS messages.
  src/main/java/org/opensearch/commons/destination/message/LegacyDestinationType.java
  src/main/java/org/opensearch/commons/destination/message/LegacySNSMessage.java
  src/main/java/org/opensearch/commons/destination/util/Util.java
  src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequest.kt
  src/test/java/org/opensearch/commons/destination/message/LegacySNSMessageTest.java
  src/test/java/org/opensearch/commons/destination/util/UtilTest.java
Labels: backport 2.x, backport 2.3

#292 fix security-analytics alerting findings api integration
  src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponse.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/FindingDocument.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/FindingWithDocs.kt
Labels: backport 2.x

#294 fix findings parsing logic introduced by pr #292
  src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponse.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/FindingDocument.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/FindingWithDocs.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
Labels: backport 2.x
