Repository opensearch-project/common-utils, pull requests merged in 2023-09, with the labels that each got.

#518 Updates demo certs used in rest tests
  src/test/resources/sample.pem
  src/test/resources/test-kirk.jks
Labels: backport 2.x, v2.10.0, backport 2.10

#511 obfuscate ip addresses in alert error message
  src/main/kotlin/org/opensearch/commons/alerting/alerts/AlertError.kt
  src/test/kotlin/org/opensearch/commons/alerting/alerts/AlertErrorTests.kt
Labels: backport 2.x, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.9, backport 2.10, backport 2.8

#531 Adds 2.10.0.0 release notes
  release-notes/opensearch-common-utils.release-notes-2.10.0.0.md
Labels: backport 2.x, backport 2.10
