Repository opensearch-project/common-utils, pull requests merged in 2023-03, with the labels that each got.

#376 Add auto Github release workflow
  .github/workflows/auto-release.yml
Labels: backport 1.3, backport 2.x

#381 Fix SNS regex for validation on notification channel to support SNS FIFO topics.
  src/main/kotlin/org/opensearch/commons/notifications/model/Sns.kt
  src/test/kotlin/org/opensearch/commons/notifications/model/SnsTests.kt
Labels: backport 2.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#380 Added workflow as a composite monitor
  src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequest.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponse.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowRequest.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponse.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
  src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponse.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/CompositeInput.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Finding.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Sequence.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowInput.kt
  src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
  src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequestTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Labels: composite-monitors
