Repository opensearch-project/common-utils, pull requests merged in 2024-04, with the labels that each got.

#598 Updates sample cert and admin keystore
  src/test/resources/sample.pem
  src/test/resources/test-kirk.jks
Labels: backport 2.x

#633 Added validation for the new clusters field.
  src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
  src/main/kotlin/org/opensearch/commons/alerting/util/CommonUtilsException.kt
  src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
  src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
Labels: backport 2.x, backport 2.12, backport 2.13

#636 [Backport 2.x] Added validation for the new clusters field. (#633)
  src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
  src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
  src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
Labels: backport 2.12, backport 2.13

#645 Wrapped URI syntax exception in IllegalArgument exception.
  src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
Labels: backport 2.x, backport 2.13
