Repository opensearch-project/common-utils, pull requests merged in 2024-06, with the labels that each got.

#672 Add 2.15 release notes
  release-notes/opensearch-common-utils.release-notes-2.15.0.0.md
Labels: backport 2.x

#678 Fixing DataSources Parsing Errors
  src/main/kotlin/org/opensearch/commons/alerting/model/DataSources.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Labels: backport 2.x

#671 Adding EntityType to Comment Model
  release-notes/opensearch-common-utils.release-notes-2.15.0.0.md
  src/main/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequest.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Comment.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequestTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentResponseTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Labels: backport 2.x

#683 [Backport 2.x] Adding EntityType to Comment Model (#671)
  release-notes/opensearch-common-utils.release-notes-2.15.0.0.md
  src/main/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequest.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Comment.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequestTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentResponseTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
  src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Labels: backport 2.15

#685 updated the 2.15 release-notes
  release-notes/opensearch-common-utils.release-notes-2.15.0.0.md
Labels: backport 2.x, backport 2.15
