Repository opensearch-project/common-utils, pull requests merged in 2025-04, with the labels that each got.

#811 add version checks in serde flows for Fan out request changes since 2.15
  src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/IndexExecutionContext.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
  src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowRunContext.kt
Labels: backport 2.x

#821 Remove beta1 qualifier
  build.gradle
Labels: release, v3.0.0, backport main

#824 Update 3.0.0.0 releasenotes
  release-notes/opensearch-common-utils.release-notes-3.0.0.0.md
Labels: release, v3.0.0, backport 3.0
